-- student definition

CREATE TABLE student (
	NAME TEXT,
	DATE_OF_BIRTH TEXT,
	CURRENT_CLASS TEXT,
	DATE_OF_JOIN TEXT,
	IDENTIFIER_ID TEXT,
	IDENTIFIER_TYPE TEXT,
	LAST_4_DIGIT_OF_IDENTIFIER TEXT,
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	LAST_UPDATED TEXT,
	INSERTED_ON TEXT,
	CATEGORY TEXT
, CLASS_JOINED TEXT);

-- guardian_details definition

CREATE TABLE guardian_details (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	NAME TEXT,
	RELATION_TYPE TEXT,
	MOBILE_NUMBER TEXT,
	YEAR_OF_BIRTH INTEGER,
	STUDENT_IDS BLOB
);

-- fee_structure_yearly definition

CREATE TABLE "fee_structure_yearly" (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	CLASS TEXT,
	START_DATE TEXT,
	END_DATE TEXT,
	IS_ACTIVE INTEGER DEFAULT (1),
	AMOUNT_TO_PAY REAL DEFAULT (0),
	INSERTED_ON TEXT,
	UPDATED_ON TEXT
);


-- student_annual_fee definition

CREATE TABLE student_annual_fee (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	STUDENT_ID INTEGER,
	CLASS TEXT,
	FEE_AMOUNT REAL,
	PAYMENT_START_DATE TEXT,
	PAYMENT_LAST_DATE TEXT
);


-- billing_details definition

CREATE TABLE billing_details (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	STUDENT_ID INTEGER,
	CLASS TEXT,
	NOTES TEXT,
	PAID_ON TEXT,
	AMOUNT_PAID REAL,
	PAYMENT_METHOD TEXT,
	PAYMENT_NOTES TEXT,
	BALANCE_AMOUNT_TO_PAY REAL,
	INSERTED_ON TEXT,
	UPDATED_ON TEXT
, AMOUNT_IN_WORDS TEXT);

-- identifier_table definition

CREATE TABLE identifier_table (
	ID TEXT,
	IDENTIFIER_TYPE TEXT,
	IDENTIFIER_VALUE_AES TEXT,
	LAST_4_DIGIT_OF_IDENTIFIER TEXT,
	NOUNCE TEXT
, TAG TEXT);